// <auto-generated />
using System;
using Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace myApi.Data.Migrations
{
    [DbContext(typeof(RISDbContext))]
    [Migration("20230202183420_InitialMigration")]
    partial class InitialMigration
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Data.Models.Patient", b =>
                {
                    b.Property<int>("PatientId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("PatientId"), 1L, 1);

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gendre")
                        .HasColumnType("int");

                    b.Property<string>("Givenid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Insertdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Middlename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationalidnumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("PatientId");

                    b.ToTable("patients");

                    b.HasData(
                        new
                        {
                            PatientId = 1,
                            Firstname = "patient1",
                            Gendre = 0,
                            Givenid = "11111",
                            Insertdate = new DateTime(2023, 2, 2, 21, 34, 19, 393, DateTimeKind.Local).AddTicks(9019),
                            Lastname = "father1",
                            Nationalidnumber = "11111111111"
                        },
                        new
                        {
                            PatientId = 2,
                            Firstname = "patient2",
                            Gendre = 0,
                            Givenid = "22222",
                            Insertdate = new DateTime(2023, 2, 2, 21, 34, 19, 393, DateTimeKind.Local).AddTicks(9150),
                            Lastname = "father2",
                            Nationalidnumber = "11111111111"
                        },
                        new
                        {
                            PatientId = 3,
                            Firstname = "patient3",
                            Gendre = 0,
                            Givenid = "33333",
                            Insertdate = new DateTime(2023, 2, 2, 21, 34, 19, 393, DateTimeKind.Local).AddTicks(9166),
                            Lastname = "father3",
                            Nationalidnumber = "11111111111"
                        },
                        new
                        {
                            PatientId = 4,
                            Firstname = "patient4",
                            Gendre = 0,
                            Givenid = "44444",
                            Insertdate = new DateTime(2023, 2, 2, 21, 34, 19, 393, DateTimeKind.Local).AddTicks(9180),
                            Lastname = "father4",
                            Nationalidnumber = "11111111111"
                        },
                        new
                        {
                            PatientId = 5,
                            Firstname = "patient5",
                            Gendre = 0,
                            Givenid = "55555",
                            Insertdate = new DateTime(2023, 2, 2, 21, 34, 19, 393, DateTimeKind.Local).AddTicks(9194),
                            Lastname = "father5",
                            Nationalidnumber = "11111111111"
                        });
                });
#pragma warning restore 612, 618
        }
    }
}
