// <auto-generated />
using System;
using Data.Models;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace myApi.Data.Migrations
{
    [DbContext(typeof(RISDbContext))]
    [Migration("20230203180834_AddOrderTable")]
    partial class AddOrderTable
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "6.0.7")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder, 1L, 1);

            modelBuilder.Entity("Data.Models.Patient", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<string>("Firstname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<int?>("Gendre")
                        .HasColumnType("int");

                    b.Property<string>("Givenid")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime>("Insertdate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Lastname")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Middlename")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Nationalidnumber")
                        .IsRequired()
                        .HasMaxLength(11)
                        .HasColumnType("nvarchar(11)");

                    b.HasKey("Id");

                    b.ToTable("patients");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Firstname = "patient1",
                            Gendre = 0,
                            Givenid = "11111",
                            Insertdate = new DateTime(2023, 2, 3, 21, 8, 31, 934, DateTimeKind.Local).AddTicks(9173),
                            Lastname = "father1",
                            Nationalidnumber = "11111111111"
                        },
                        new
                        {
                            Id = 2,
                            Firstname = "patient2",
                            Gendre = 0,
                            Givenid = "22222",
                            Insertdate = new DateTime(2023, 2, 3, 21, 8, 31, 934, DateTimeKind.Local).AddTicks(9342),
                            Lastname = "father2",
                            Nationalidnumber = "11111111111"
                        },
                        new
                        {
                            Id = 3,
                            Firstname = "patient3",
                            Gendre = 0,
                            Givenid = "33333",
                            Insertdate = new DateTime(2023, 2, 3, 21, 8, 31, 934, DateTimeKind.Local).AddTicks(9363),
                            Lastname = "father3",
                            Nationalidnumber = "11111111111"
                        },
                        new
                        {
                            Id = 4,
                            Firstname = "patient4",
                            Gendre = 0,
                            Givenid = "44444",
                            Insertdate = new DateTime(2023, 2, 3, 21, 8, 31, 934, DateTimeKind.Local).AddTicks(9619),
                            Lastname = "father4",
                            Nationalidnumber = "11111111111"
                        },
                        new
                        {
                            Id = 5,
                            Firstname = "patient5",
                            Gendre = 0,
                            Givenid = "55555",
                            Insertdate = new DateTime(2023, 2, 3, 21, 8, 31, 934, DateTimeKind.Local).AddTicks(9667),
                            Lastname = "father5",
                            Nationalidnumber = "11111111111"
                        });
                });

            modelBuilder.Entity("Data.Models.RadOrder", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"), 1L, 1);

                    b.Property<DateTime>("Insertdate")
                        .HasColumnType("datetime2");

                    b.Property<int>("PatientId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("PatientId");

                    b.ToTable("RadOrder");
                });

            modelBuilder.Entity("Data.Models.RadOrder", b =>
                {
                    b.HasOne("Data.Models.Patient", "patient")
                        .WithMany("Orders")
                        .HasForeignKey("PatientId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("patient");
                });

            modelBuilder.Entity("Data.Models.Patient", b =>
                {
                    b.Navigation("Orders");
                });
#pragma warning restore 612, 618
        }
    }
}
